version: '3.9'

# networks:
#   bestprice:
#     driver: bridge

services:
  frontend:
    build:
      context: ../frontend/
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000      
    restart: "no"
    deploy:
      mode: replicated
      replicas: 1
    # networks:
    #   - bestprice
    environment:
      SERVER_URL: "http://192.168.50.141:5006"
      TZ: 'Asia/Seoul'