version: '3.9'

services:
  nginx:
    build: 
      context: ../nginx/
      dockerfile: Dockerfile
    ports:
      - 6443:443
      - 6001:80
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./pilseong.net_ecc/:/opt/
    environment:
      - TZ=Asia/Seoul